spring.application.name=Hotel Booking

server.port=9091
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_booking_db
spring.datasource.username=root
spring.datasource.password=248888

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
